# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marshal < Formula
  desc "Free, self-hosted process & fleet manager — an open alternative to PM2 / PM2 Plus"
  homepage "https://github.com/REDDE4D/marshal-pm"
  version "0.8.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/REDDE4D/marshal-pm/releases/download/v0.8.0/marshal_0.8.0_darwin_amd64.tar.gz"
      sha256 "1ce0149927be8eb93ef1fc1a22120b828978236b7ef7104dcc26074daeacbd0c"

      define_method(:install) do
        bin.install "marshal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/REDDE4D/marshal-pm/releases/download/v0.8.0/marshal_0.8.0_darwin_arm64.tar.gz"
      sha256 "332884aac628cebaaa550dfb5bfb314736cecdf8700db265ba5e53b83097b44c"

      define_method(:install) do
        bin.install "marshal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/REDDE4D/marshal-pm/releases/download/v0.8.0/marshal_0.8.0_linux_amd64.tar.gz"
      sha256 "f1502a16896753634cce61e102b129d4479b777dd7a81e14749df5f320c65577"
      define_method(:install) do
        bin.install "marshal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/REDDE4D/marshal-pm/releases/download/v0.8.0/marshal_0.8.0_linux_arm64.tar.gz"
      sha256 "6712a0dbff5d06bb141a43ab6d41881fefc82d87913b2680d1f607b679b89ff2"
      define_method(:install) do
        bin.install "marshal"
      end
    end
  end

  test do
    system "#{bin}/marshal", "--version"
  end
end
